// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVSGxg24w49URTCTsqEnAQJMCs7QLILzU',
    appId: '1:213898240694:web:95643c150e9e5d368fbc17',
    messagingSenderId: '213898240694',
    projectId: 'mynotes-mk-notes-projects',
    authDomain: 'mynotes-mk-notes-projects.firebaseapp.com',
    storageBucket: 'mynotes-mk-notes-projects.appspot.com',
    measurementId: 'G-29XYVHJ8FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCc12d5bSO0Q71cnWZRlKZ3QaxmYVQNRI',
    appId: '1:213898240694:android:094e4ce76cbbfe6a8fbc17',
    messagingSenderId: '213898240694',
    projectId: 'mynotes-mk-notes-projects',
    storageBucket: 'mynotes-mk-notes-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqR-t4L-wFkpIRBEmYqtOt-EZGzTaLXWU',
    appId: '1:213898240694:ios:27053511235586e08fbc17',
    messagingSenderId: '213898240694',
    projectId: 'mynotes-mk-notes-projects',
    storageBucket: 'mynotes-mk-notes-projects.appspot.com',
    iosClientId: '213898240694-q4qg07e5v8t8ikp0jme0480fhndg3nql.apps.googleusercontent.com',
    iosBundleId: 'com.mk.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqR-t4L-wFkpIRBEmYqtOt-EZGzTaLXWU',
    appId: '1:213898240694:ios:27053511235586e08fbc17',
    messagingSenderId: '213898240694',
    projectId: 'mynotes-mk-notes-projects',
    storageBucket: 'mynotes-mk-notes-projects.appspot.com',
    iosClientId: '213898240694-q4qg07e5v8t8ikp0jme0480fhndg3nql.apps.googleusercontent.com',
    iosBundleId: 'com.mk.mynotes',
  );
}
